### PR TITLE
Update node configure

### PR DESCRIPTION
**Pull request by andreif**

### CODE REVIEW

**Comment by andreif** [comment]
`npm ERR! Error: EACCES, open '/home/ubuntu/.npm/fcfaba5d-babel-5-6-3.lock'`

**Comment by andreif** [comment]
Hm, it will probably happen again, fixed now with `ubuntu@myproj-dev:~$ sudo chown myproj:myproj -R .npm`

**Comment by andreif** [comment]
Oh damn, ubuntu, wrong user...

**Comment by andreif** [comment]
Alright, I am running out of time and cannot debug it so have to use chown.

**Comment by kyrias** [comment]
The problem is that the sudo command that blues uses for the context manager keeps the ubuntu user's `HOME` env var instead of setting the new one.

To work around that you'll have to do something like the following, like I did in `bower_install`

```
home = 'export HOME={}'.format(project_home())
```
Then after that use `with prefix(home)...`

**Comment by andreif** [comment]
Aaah, works now, thanks!

**Pull request merged**
